# Website's icon url.
favicon: /images/favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
# open_graph:
#   twitter_id:
#   twitter_site:
#   google_plus:
#   fb_admins:
#   fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: /images/title-alpha.png

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light
  # Date format: relative | full | relative_full | full_relative
  date_format: relative

# Navigation bar menu links.
menu:
  归档: /archives
  关于: /about
  链接: /links
  文档: https://docs.opengiraffes.top
  应用商店: https://store.opengiraffes.top

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: true

# Share plugin settings.
# share:
#   type: sharethis
#   install_url:

# Comment plugin settings.
# comment:
#   type: 
#   shortname:

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/openGiraffes
