# Navigation bar menu links.
menu:
  Archives: /en/archives
  About: /en/about
  Links: /en/links
  Documentation: https://docs.opengiraffes.top
  App Store: https://store.opengiraffes.top
  Chatroom: /chat