# Navigation bar menu links.
menu:
  Archives: /en/archives
  About: /en/about.html
  Links: /en/links.html
  Documentation: https://docs.opengiraffes.top
  App Store: https://store.opengiraffes.top
  Chatroom: /chat.html
